# -*- coding: utf-8 -*-
"""TrabalhoIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mr8gUQe7IVqE0jI1qYc9oIcK_W4VZn8Y
"""

import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


SHEET_ID = "1G-pp7P9sBWLy0_ohm6vxghQdVAp0u_GDjmKuECM00lc"
GID = "465442527"
url_tsv = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=tsv&gid={GID}"

# TSV + vírgula decimal
df = pd.read_csv(url_tsv, sep="\t", decimal=",")

print("Colunas lidas:", list(df.columns))
display(df.head())

# Suas novas variáveis independentes
FEATURES = ["habitantes", "industrias", "temperatura_media"]

# O que você quer prever
TARGET = "consumo_energia"

for col in FEATURES :
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Normaliza o target e remove linhas inválidas
df[TARGET] = df[TARGET].astype(str).str.strip().str.lower()
df = df.dropna(subset=FEATURES + [TARGET]).copy() #remove linhas com valores inválidos

print("\nDistribuição do target:")
print(df[TARGET].value_counts())

le = LabelEncoder()
y_all = le.fit_transform(df[TARGET])
X_all = df[FEATURES].values

print("\nClasses:", list(le.classes_))
print("Total linhas válidas:", len(df))

RANDOM_STATE = 42
df_shuffled = df.sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)
limite_teste=int(len(df)*0.20) # Split : 20% teste + 80% treino
test_df  = df_shuffled.iloc[:limite_teste].copy()
train_df = df_shuffled.iloc[limite_teste:len(df)].copy()
X_train = train_df[FEATURES].values
y_train = le.transform(train_df[TARGET])
X_test  = test_df[FEATURES].values
y_test  = le.transform(test_df[TARGET])
print("\nTreino:", len(train_df), "| Teste:", len(test_df))

def dist_classes(frame, target_col, titulo):
    vc = frame[target_col].value_counts(dropna=False)
    pct = (vc / len(frame) * 100).round(1)
    out = pd.DataFrame({"qtd": vc, "%": pct})
    print(f"\n=== {titulo} (n={len(frame)}) ===")
    display(out)

dist_classes(df, TARGET, "Dataset completo")
dist_classes(train_df, TARGET, "Treino")
dist_classes(test_df, TARGET, "Teste")

# Modelo KNN
K = 5
WEIGHTS = "distance"  # "uniform" ou "distance"

model = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=K, weights=WEIGHTS))
])

model.fit(X_train, y_train)

# Avaliação
y_pred = model.predict(X_test)

print("\nFeatures usadas:", FEATURES)
print("Acurácia:", accuracy_score(y_test, y_pred))
print("\nRelatório:")

# LINHA CORRIGIDA AQUI: Adicionamos labels e zero_division
print(classification_report(
    y_test,
    y_pred,
    labels=range(len(le.classes_)), # Força a mostrar todas as classes
    target_names=le.classes_,
    zero_division=0                 # Evita avisos de divisão por zero se uma classe não aparecer
))

print("Matriz de confusão (real x previsto):")
print(confusion_matrix(y_test, y_pred))

# Resultado detalhado do teste
test_df["classe_prevista"] = le.inverse_transform(y_pred)
# Exibe a cidade, as features usadas, o consumo real e o previsto
display(test_df[["cidade"] + FEATURES + [TARGET, "classe_prevista"]])

# ========= Árvore de decisão =========
from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

# "simples" e legível para aula (ajuste se quiser):
tree = DecisionTreeClassifier(
    max_depth=3,          # controla complexidade/legibilidade
    random_state=RANDOM_STATE
)

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

print("\n=== Árvore de decisão ===")
print("Features usadas:", FEATURES)
print("Acurácia:", accuracy_score(y_test, y_pred_tree))
print("\nRelatório:")

# CORREÇÃO APLICADA AQUI: Adicionado labels e zero_division
print(classification_report(
    y_test,
    y_pred_tree,
    labels=range(len(le.classes_)),
    target_names=le.classes_,
    zero_division=0
))

print("Matriz de confusão (real x previsto):")
print(confusion_matrix(y_test, y_pred_tree))

# Resultado detalhado do teste
test_df["classe_prevista_arvore"] = le.inverse_transform(y_pred_tree)
display(test_df[["cidade"] + FEATURES + [TARGET, "classe_prevista_arvore"]])

# desenhar a árvore
plt.figure(figsize=(18, 10))
plot_tree(
    tree,
    feature_names=FEATURES,
    class_names=list(le.classes_),
    filled=True,
    rounded=True,
    impurity=True
)
plt.title("Árvore de Decisão (max_depth=3) — Previsão de Consumo de Energia")
plt.show()